# Generated by Django 5.2.12 on 2026-05-10 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0004_companysocialprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagedPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                            ("reddit", "Reddit"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("title", models.TextField(blank=True, default="")),
                ("like_count", models.PositiveIntegerField(blank=True, null=True)),
                ("share_count", models.PositiveIntegerField(blank=True, null=True)),
                ("comment_count", models.PositiveIntegerField(blank=True, null=True)),
                ("view_count", models.PositiveIntegerField(blank=True, null=True)),
                ("scraped_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engaged_posts",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-scraped_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "url"),
                        name="engagement_engagedpost_company_url_uniq",
                    )
                ],
            },
        ),
    ]
