# Generated by Django 5.2.12 on 2026-03-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=150)),
                ("professional_email", models.EmailField(max_length=254, unique=True)),
                ("company_name", models.CharField(max_length=150)),
                ("sector", models.CharField(max_length=100)),
                ("company_size", models.CharField(max_length=50)),
                ("goal", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
