# Generated by Django 5.2.12 on 2026-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accessrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="company_size",
            field=models.CharField(
                choices=[
                    ("1-10", "1-10 موظفين"),
                    ("10-50", "10-50 موظف"),
                    ("50-200", "50-200 موظف"),
                    ("200+", "200+ موظف"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="sector",
            field=models.CharField(
                choices=[
                    ("ecommerce", "تجارة إلكترونية"),
                    ("finance", "بنك / مالية"),
                    ("telecom", "اتصالات"),
                    ("services", "خدمات"),
                    ("other", "أخرى"),
                ],
                max_length=50,
            ),
        ),
    ]
