# Generated by Django 5.2.12 on 2026-04-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_accessrequest_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="approved_user",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="is_approved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="is_reviewed",
            field=models.BooleanField(default=False),
        ),
    ]
