# Generated by Django 5.2.12 on 2026-04-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_activationtoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activationtoken",
            name="access_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activation_tokens",
                to="accounts.accessrequest",
            ),
        ),
    ]
