# Generated by Django 5.2.12 on 2026-04-27 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("companies", "0004_companysocialprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("negative_pct_above", "نسبة السلبي تتجاوز الحد"),
                            ("positive_pct_below", "نسبة الإيجابي تنخفض عن الحد"),
                            ("negative_count_above", "عدد السلبيات يتجاوز الحد اليومي"),
                            ("volume_spike", "حجم المنشورات اليومية يتجاوز الحد"),
                            ("keyword_spike", "كلمة مفتاحية تتجاوز الحد"),
                            ("sentiment_drop", "انخفاض حاد في الإيجابي مقارنة بالأمس"),
                            ("negative_streak", "السلبي هو الغالب لعدة أيام متتالية"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "threshold",
                    models.FloatField(
                        help_text="الحد الرقمي — نسبة مئوية أو عدد حسب نوع القاعدة"
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="فقط لنوع keyword_spike",
                        max_length=200,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالٍ"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_rules",
                        to="companies.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالٍ"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("triggered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="companies.company",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alerts",
                        to="alerts.alertrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-triggered_at"],
            },
        ),
    ]
