# Generated by Django 5.0.3 on 2026-04-12 13:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_company_7fc2c6_idx",
            old_name="posts_post_company_0fada8_idx",
        ),
        migrations.RenameIndex(
            model_name="post",
            new_name="posts_post_company_b62666_idx",
            old_name="posts_post_company_6e3a22_idx",
        ),
    ]
