# Generated by Django 5.2.12 on 2026-04-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "posts",
            "0002_rename_posts_post_company_0fada8_idx_posts_post_company_7fc2c6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="source",
            field=models.CharField(
                choices=[
                    ("gdelt", "GDELT"),
                    ("rss", "RSS"),
                    ("youtube", "YouTube"),
                    ("twitter", "Twitter"),
                    ("google_news", "Google News"),
                    ("reddit", "Reddit"),
                    ("hackernews", "Hacker News"),
                    ("facebook", "Facebook"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
