# Generated by Django 5.2.12 on 2026-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_post_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="source",
            field=models.CharField(
                choices=[
                    ("rss", "RSS"),
                    ("youtube", "YouTube"),
                    ("twitter", "Twitter"),
                    ("google_news", "Google News"),
                    ("reddit", "Reddit"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("manual", "Manual"),
                ],
                max_length=20,
            ),
        ),
    ]
