# Generated by Django 5.2.12 on 2026-04-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0004_companysocialprofile"),
        ("posts", "0006_alter_post_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sentiment",
            field=models.CharField(
                blank=True,
                choices=[
                    ("positive", "Positive"),
                    ("neutral", "Neutral"),
                    ("negative", "Negative"),
                ],
                db_index=True,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment_at",
            field=models.DateTimeField(
                blank=True, help_text="When sentiment was last classified.", null=True
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment_score",
            field=models.FloatField(
                blank=True,
                help_text="Confidence score of the predicted sentiment (0.0 – 1.0).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="sentiment_scores",
            field=models.JSONField(
                blank=True,
                help_text="Full probability distribution: {negative, neutral, positive}.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["company", "sentiment"], name="posts_post_company_ed314c_idx"
            ),
        ),
    ]
