# Generated by Django 5.2.12 on 2026-04-13 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_backfill_default_company_memberships"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["keyword"],
                "unique_together": {("company", "keyword")},
            },
        ),
    ]
