# Generated by Django 5.2.12 on 2026-04-21 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0003_companykeyword"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanySocialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("rss", "RSS Feed"),
                            ("youtube_channel", "YouTube Channel"),
                            ("x", "X / Twitter"),
                        ],
                        max_length=30,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to temporarily disable this source without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_profiles",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["platform"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "platform", "url"),
                        name="companies_socialprofile_company_platform_url_uniq",
                    )
                ],
            },
        ),
    ]
