# Generated by Django 5.2.12 on 2026-05-13 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nps_score",
                    models.PositiveSmallIntegerField(
                        help_text="0–10 Net Promoter Score"
                    ),
                ),
                (
                    "accuracy_rating",
                    models.PositiveSmallIntegerField(
                        help_text="Sentiment accuracy rating 1–5"
                    ),
                ),
                (
                    "usability_rating",
                    models.PositiveSmallIntegerField(
                        help_text="Dashboard usability rating 1–5"
                    ),
                ),
                (
                    "coverage_rating",
                    models.PositiveSmallIntegerField(
                        help_text="Scraping coverage rating 1–5"
                    ),
                ),
                ("comment", models.TextField(blank=True, default="")),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Name shown on homepage (e.g. 'Ahmed, Mobilis'). Auto-filled if blank.",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Platform Feedback",
                "verbose_name_plural": "Platform Feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
